spring:
  config:
    import: optional:file:.env
  datasource:
    url: ${JDBC_DRIVER_VERSION}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog.xml
    enabled: true
